### ISSUE TITLE
Перенос заголовков

### ISSUE THREAD

**Issue by ialeshqa** [hookprod/intergaz#19]
https://yadi.sk/i/TDt1tMBLotYni в две строки сделать заголовок

**Comment by ialeshqa** [comment]
в планшетной версии и в широкой десктопной, а то как говно выглядит нелогичное https://yadi.sk/i/hKtsSQs2otZ87

**Comment by d3head** [comment]
Ясделялъ

**Comment by ialeshqa** [comment]
на продакшене нету

**Comment by d3head** [comment]
Слепой, расширяй десктопную версию и увидишь

**Comment by ialeshqa** [comment]
https://yadi.sk/i/eFA_RISIox8Ch
