### ISSUE TITLE
Кнопка плэй на фотке

### ISSUE THREAD

**Issue by ialeshqa** [hookprod/intergaz#2]
https://yadi.sk/i/urUrlDFSoY7bt

**Comment by d3head** [comment]
Done

**Comment by ialeshqa** [comment]
давай ховера добавим, меняя цвет треугольника на цвет кнопки 

https://yadi.sk/i/XaAJUseLotW36

**Comment by ialeshqa** [comment]
+ кнопка прыгает при релоаде http://d.pr/v/1ijlx
