### ISSUE TITLE
Заменить контент в блоке

### ISSUE THREAD

**Issue by ialeshqa** [hookprod/intergaz#27]
https://yadi.sk/i/3-Up-U3notbbM

новая фотка: http://d.pr/i/10139

текст тот же

подпись: 
Евгений Карев
Генеральный директор

**Comment by d3head** [comment]
Доне

**Comment by ialeshqa** [comment]
вот те квадратная фотка https://drive.google.com/file/d/0BygJhZyOXiawZUxKWVRsenk3MzA/view?usp=sharing

**Comment by ialeshqa** [comment]
попробуй эту вставить, без обрезания круга через css https://drive.google.com/file/d/0BygJhZyOXiawS2ZmQUZIbXBkUTQ/view?usp=sharing
