### ISSUE TITLE
Переключатель языков

### ISSUE THREAD

**Issue by ialeshqa** [hookprod/intergaz#4]
сделать ссылками https://yadi.sk/i/9d4YjiYgoY7mT

**Comment by d3head** [comment]
Done

**Comment by ialeshqa** [comment]
русская версия активна, нахуя ты ее ссылкой сделал, китаец? думать кто будет? или ты как робот? :) https://yadi.sk/i/oWzFmsSzotVhf

ссылкам на англ и латв версии добавить ховеры (андерлайн)

**Comment by ialeshqa** [comment]
а в мобильной/планшетной само что ли сделается? https://yadi.sk/i/qFxYOy0CotZFw

**Comment by d3head** [comment]
што?
предыдущее готово
