### ISSUE TITLE
Обрезанная иконка

### ISSUE THREAD

**Issue by ialeshqa** [hookprod/intergaz#7]
https://yadi.sk/i/R9yvkP4IoY8eY

**Comment by d3head** [comment]
Она такая в в макете

**Comment by ialeshqa** [comment]
обновили иконку в десктопном макете

**Comment by d3head** [comment]
Менеджер, ссылку дай

**Comment by ialeshqa** [comment]
у тебя же есть доступ к папке епта https://www.dropbox.com/sh/ge7410ltczz7uq6/AABUvmWT3yZpS1KL0u4l1YKPa?dl=0
